# Generated by Django 4.2.7 on 2023-12-30 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_restaurant_livraison_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 1, 46, 13, 916150, tzinfo=datetime.timezone.utc)),
        ),
    ]
