# Generated by Django 4.2.7 on 2023-12-30 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 22, 31, 15, 318315, tzinfo=datetime.timezone.utc)),
        ),
    ]
