# Generated by Django 4.2.7 on 2023-12-30 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_commande_date_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='plat',
        ),
        migrations.AddField(
            model_name='plat',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='shopapp.ingredient'),
        ),
        migrations.AddField(
            model_name='platmenu',
            name='nb_etoile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 23, 9, 16, 248049, tzinfo=datetime.timezone.utc)),
        ),
    ]
