# Generated by Django 4.2.7 on 2023-12-31 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_simple_user_date_of_birth'),
        ('shopapp', '0010_remove_ingredient_plat_plat_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platmenu',
            name='nb_etoile',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 10, 5, 41, 267060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ApreciationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_etoile', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.platmenu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.simple_user')),
            ],
        ),
    ]
