# Generated by Django 4.2.7 on 2023-12-31 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_remove_platmenu_nb_etoile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 19, 15, 13, 218233, tzinfo=datetime.timezone.utc)),
        ),
    ]
