# Generated by Django 4.2.7 on 2024-01-01 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0012_alter_commande_date_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercherPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_recherche', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 18, 24, 37, 505320, tzinfo=datetime.timezone.utc))),
                ('resultat', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 18, 24, 37, 504127, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RechercherParDescription',
            fields=[
                ('rechercherplat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopapp.rechercherplat')),
                ('texte_description', models.TextField()),
            ],
            bases=('shopapp.rechercherplat',),
        ),
        migrations.CreateModel(
            name='RechercherParImage',
            fields=[
                ('rechercherplat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopapp.rechercherplat')),
                ('image', models.ImageField(upload_to='resto_img')),
            ],
            bases=('shopapp.rechercherplat',),
        ),
    ]
