# Generated by Django 4.2.7 on 2024-01-01 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_rechercherplat_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 19, 23, 19, 263313, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rechercherplat',
            name='date_recherche',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 19, 23, 19, 264211, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rechercherplat',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
