# Generated by Django 4.2.7 on 2024-01-01 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 19, 46, 16, 84108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rechercherparimage',
            name='image',
            field=models.ImageField(upload_to='recherche_img'),
        ),
        migrations.AlterField(
            model_name='rechercherplat',
            name='date_recherche',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 19, 46, 16, 85248, tzinfo=datetime.timezone.utc)),
        ),
    ]
