# Generated by Django 4.2.7 on 2024-01-05 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_simple_user_date_of_birth'),
        ('shopapp', '0015_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 0, 25, 16, 458769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rechercherplat',
            name='date_recherche',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 0, 25, 16, 463252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PlatHealthPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_pb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.health_problem')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.plat')),
            ],
        ),
    ]
