# Generated by Django 4.2.7 on 2024-01-07 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 19, 21, 18, 732021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rechercherplat',
            name='date_recherche',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 19, 21, 18, 736349, tzinfo=datetime.timezone.utc)),
        ),
    ]
