# Generated by Django 4.2.7 on 2024-01-19 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_commande_quantite_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_delai',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 5, 56, 46, 514162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 5, 56, 46, 514113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rechercherplat',
            name='date_recherche',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 5, 56, 46, 517023, tzinfo=datetime.timezone.utc)),
        ),
    ]
