version: '3.8'
services : 
  resto:
    build:
      context: ./RestoUser
      dockerfile: Dockerfile
    command: 'python RestoUser/manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - dbresto
      - rabbitmq

  user:
    build:
      context: ./User
      dockerfile: Dockerfile
    command: 'python User/manage.py runserver 0.0.0.0:8000'
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - dbuser
      - rabbitmq

  queueresto:
    build:
      context: ./User
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - dbresto
      - rabbitmq

  queueuser:
    build:
      context: User
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - dbuser
      - rabbitmq


  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"

  dbresto:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME_RESTO}
      #MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      
    volumes:
      - ./RestoUser/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  dbuser:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME_USER}
      #MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
      
    volumes:
      - ./User/.dbdata:/var/lib/mysql
    ports:
      - 33067:3306