# Generated by Django 4.2.7 on 2023-11-10 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchantuserapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant_user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 10, 23, 6, 56, 684386, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="merchant_user",
            name="restorent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="merchantuserapp.restorent",
            ),
        ),
    ]
