# Generated by Django 4.2.7 on 2023-11-10 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchantuserapp", "0004_alter_merchant_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant_user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 10, 23, 32, 6, 578275, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="merchant_user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
