# Generated by Django 4.2.7 on 2023-11-24 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchantuserapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_img')),
                ('gender', models.CharField(choices=[('-', 'None'), ('f', 'Female'), ('m', 'Male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Validée', 'Validée'), ('Annulée', 'Annulée')], max_length=10)),
                ('date_commande', models.DateTimeField(default=datetime.datetime(2023, 11, 24, 20, 2, 34, 140053, tzinfo=datetime.timezone.utc))),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchantuserapp.plat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchantuserapp.restaurant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.simpleuser')),
            ],
        ),
    ]
