# Generated by Django 4.2.7 on 2023-11-24 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_commande_numero_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 21, 15, 59, 763201, tzinfo=datetime.timezone.utc)),
        ),
    ]
