# Generated by Django 4.2.7 on 2023-12-30 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_commande_date_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 22, 32, 6, 782819, tzinfo=datetime.timezone.utc)),
        ),
    ]
