# Generated by Django 4.2.7 on 2023-12-30 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_remove_simpleuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 23, 11, 9, 561364, tzinfo=datetime.timezone.utc)),
        ),
    ]
