# Generated by Django 4.2.7 on 2024-01-19 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_commande_quantite_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 20, 35, 9, 580165, tzinfo=datetime.timezone.utc)),
        ),
    ]
