# Generated by Django 4.2.7 on 2024-01-19 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_delai',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 20, 39, 6, 39030, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 20, 39, 6, 38969, tzinfo=datetime.timezone.utc)),
        ),
    ]
