# Generated by Django 4.2.7 on 2024-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_delai',
            field=models.DateField(),
        ),
    ]
