# Generated by Django 4.2.7 on 2023-11-19 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Health_Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("hypertension", "hypertension"),
                            ("hypercholestérolémie", "hypercholestérolémie"),
                            ("athérosclérose", "athérosclérose"),
                            ("diabète", "diabète"),
                            ("obésité", "obésité"),
                            ("insuffisance rénale", "insuffisance rénale"),
                            ("maladie de Crohn", "maladie de Crohn"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Simple_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        default=datetime.datetime(
                            2023,
                            11,
                            19,
                            12,
                            58,
                            27,
                            629382,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_img"),
                ),
                ("size", models.FloatField(default=0.0)),
                ("weigth", models.FloatField(default=0.0)),
                ("phone_number", models.CharField(blank=True, max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("-", "None"), ("f", "Female"), ("m", "Male")],
                        max_length=1,
                    ),
                ),
                ("longitude", models.FloatField(default=0.0)),
                ("latitude", models.FloatField(default=0.0)),
                (
                    "health_problem",
                    models.ManyToManyField(blank=True, to="userapp.health_problem"),
                ),
            ],
        ),
    ]
