# Generated by Django 4.2.7 on 2023-11-24 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hypertension', 'hypertension'), ('hypercholestérolémie', 'hypercholestérolémie'), ('athérosclérose', 'athérosclérose'), ('diabète', 'diabète'), ('obésité', 'obésité'), ('insuffisance rénale', 'insuffisance rénale'), ('maladie de Crohn', 'maladie de Crohn')], max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simple_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=datetime.datetime(2023, 11, 24, 10, 49, 10, 542680, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_img')),
                ('size', models.FloatField(default=0.0)),
                ('weigth', models.FloatField(default=0.0)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('-', 'None'), ('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('health_problem', models.ManyToManyField(blank=True, to='userapp.health_problem')),
            ],
        ),
    ]
