# Generated by Django 4.2.7 on 2023-11-24 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 11, 3, 31, 77008, tzinfo=datetime.timezone.utc)),
        ),
    ]
