# Generated by Django 4.2.7 on 2023-11-10 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simple_user",
            name="health_problem",
            field=models.ManyToManyField(blank=True, to="userapp.health_problem"),
        ),
        migrations.AlterField(
            model_name="simple_user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 10, 23, 21, 15, 159157, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
