# Generated by Django 4.2.7 on 2023-11-19 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simple_user",
            name="account",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simple_user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 19, 13, 48, 16, 750349, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
