# Generated by Django 4.2.7 on 2023-11-10 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_simple_user_health_problem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simple_user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 10, 23, 26, 7, 679771, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="simple_user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
