# Generated by Django 4.2.7 on 2023-11-19 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_simple_user_account_alter_simple_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="health_problem",
            name="name",
            field=models.CharField(
                choices=[
                    ("hypertension", "hypertension"),
                    ("hypercholestérolémie", "hypercholestérolémie"),
                    ("athérosclérose", "athérosclérose"),
                    ("diabète", "diabète"),
                    ("obésité", "obésité"),
                    ("insuffisance rénale", "insuffisance rénale"),
                    ("maladie de Crohn", "maladie de Crohn"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="simple_user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 19, 14, 8, 32, 911436, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
