# Generated by Django 4.2.7 on 2024-01-01 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_simple_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 18, 24, 33, 916315, tzinfo=datetime.timezone.utc)),
        ),
    ]
