# Generated by Django 4.2.7 on 2024-01-19 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_simple_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 5, 56, 46, 498167, tzinfo=datetime.timezone.utc)),
        ),
    ]
